# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - vehicles-amazing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Test application
        run: dotnet test --verbosity normal

      - name: Publish application
        run: dotnet publish --configuration Release --output ${{ env.DOTNET_ROOT }}/vehiclesapp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vehicles-app
          path: ${{ env.DOTNET_ROOT }}/vehiclesapp
        env:
          ACTIONS_STEP_DEBUG: true

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: vehicles-app
  
      - name: Replace SQL connection string
        run: |
          sed -i 's|"vehiclesDb": ".*"|"vehiclesDb": "'"***"'"|' appsettings.json
      - name: Display Appsettings
        run: cat appsettings.json
          
      - name: Replace SQL connection string 3
        run: |
          jq '.ConnectionStrings.vehiclesDb = $newConnectionString' --arg newConnectionString "${{ secrets.SQL_CONNECTION_STRING }}" appsettings.json > appsettings.json.tmp && mv appsettings.json.tmp appsettings.json
      - name: Display Appsettings
        run: cat appsettings.json
          
      - name: Replace SQL connection string 2
        run: |
          sed -i 's|"vehiclesDb": ".*"|"vehiclesDb": "'"${{ secrets.SQL_CONNECTION_STRING }}"'"|' appsettings.json
      - name: Display Appsettings
        run: cat appsettings.json
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vehicles-action'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
    env:
      DOTNET_ROOT: 'prod'
